stages:
  - apply
  - destroy

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - "/usr/bin/env"
    - "PATH= /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:sbin:/bin"

before_script:
  - rm -rf .terraform
  - terraform --version

apply infrastructure EC2:
  stage: apply
  script:
    - terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=$CI_COMMIT_REF_NAME/terraformstatefile-EC2-$CI_COMMIT_REF_NAME"
    - terraform apply -var="environment=$CI_COMMIT_REF_NAME" -var="key_pair=$KEY_PAIR" -target=module.timeoff_ec2 --auto-approve

apply infrastructure Fargate:
  stage: apply
  script:
    - terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=$CI_COMMIT_REF_NAME/terraformstatefile-Fargate-$CI_COMMIT_REF_NAME"
    - terraform apply -var="environment=$CI_COMMIT_REF_NAME" -var="key_pair=$KEY_PAIR" -target=module.timeofffargate --auto-approve

apply infrastructure ECS:
  stage: apply
  script:
    - terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=$CI_COMMIT_REF_NAME/terraformstatefile-ECS-$CI_COMMIT_REF_NAME"
    - terraform apply -var="environment=$CI_COMMIT_REF_NAME" -var="key_pair=$KEY_PAIR" -target=module.timeoffecs --auto-approve

destroy infrastructure EC2:
  stage: destroy
  script:
    - terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=$CI_COMMIT_REF_NAME/terraformstatefile-EC2-$CI_COMMIT_REF_NAME"
    - terraform destroy -var="environment=$CI_COMMIT_REF_NAME" -var="key_pair=$KEY_PAIR" -target=module.timeoff_ec2 --auto-approve
  dependencies:
    - apply infrastructure EC2
  when: manual

destroy infrastructure Fargate:
  stage: destroy
  script:
    - terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=$CI_COMMIT_REF_NAME/terraformstatefile-Fargate-$CI_COMMIT_REF_NAME"
    - terraform destroy -var="environment=$CI_COMMIT_REF_NAME" -var="key_pair=$KEY_PAIR" -target=module.timeofffargate --auto-approve
  dependencies:
    - apply infrastructure Fargate
  when: manual

destroy infrastructure ECS:
  stage: destroy
  script:
    - terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=$CI_COMMIT_REF_NAME/terraformstatefile-ECS-$CI_COMMIT_REF_NAME"
    - terraform destroy -var="environment=$CI_COMMIT_REF_NAME" -var="key_pair=$KEY_PAIR" -target=module.timeoffecs --auto-approve
  dependencies:
    - apply infrastructure ECS
  when: manual
